### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by yanassss**
Sprint 3 finalized changes.

### CODE REVIEW

**Review by Killaskt — APPROVED** [review]
Looks ggggreat!

**Review by ThaddG — APPROVED** [review]
Seems stable

**Comment by codemonkeman** [comment]
Not seeing any bugs here, looks good.

**Review by codemonkeman — APPROVED** [review]
Looks stable good work.

**Review by MaxH2424 — COMMENTED** [review]
Good work

**Pull request merged**
