### PR TITLE
Sprint 3 Thadd-wip into beta

### PR DESCRIPTION
**Pull request by ThaddG**

### CODE REVIEW

**Comment by Killaskt** [comment]
Great Job Thadd and Sunayana, you are an asset to this team.

**Comment by codemonkeman** [comment]
Alignment works now, good work!

**Comment by yanassss** [comment]
Approved.

**Review by Killaskt — APPROVED** [review]
Great Job Thadd and Sunayana

**Review by yanassss — COMMENTED** [review]
Good.

**Review by codemonkeman — APPROVED** [review]
Looks good guys great work.

**Review by yanassss — APPROVED** [review]

**Pull request merged**
